INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'Flauta dulce hecha en España', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'Flauta Dulce Española', 15, true, null, null, null, 'Instrumentos');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'Violín hecho en Venecia', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'Violín Venecia', 400, true, null, null, null, 'Instrumentos');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'Batería edición limitada de ACDC', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'Batería ACDC', 1500, true, null, null, null, 'Instrumentos');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'KOD, lanzado en 2018', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'KOD - J Cole', 30, true, null, null, null, 'Discografía');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), '2014 Forest Hills Drive, lanzado en 2014', TO_DATE('27/05/2019', 'DD/MM/YYYY'), '2014 Forest Hills Drive - J Cole', 20, true, null, null, null, 'Discografía');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'The Come Up, lanzado en 2007', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'The Come Up - J Cole', 10, true, null, null, null, 'Discografía');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'Sudadera Slim Shady edición limitada', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'Sudadera Slim Shady', 95, true, null, null, null, 'Otros');

INSERT INTO PRODUCTO(ID,DESCRIPCION,FECHA_PUBL,NOMBRE,PVP,STOCK,CATEGORIA_ID_CATEGORIA,LINEA_PEDIDO_ID_LINEA_PEDIDO,IMAGE,NOMBRE_CATEGORIA) VALUES (NEXTVAL('hibernate_sequence'), 'Altavoz Kriss Kross', TO_DATE('27/05/2019', 'DD/MM/YYYY'), 'Altavoz Kriss Kross', 450, true, null, null, null, 'Otros');


INSERT INTO USUARIO(ID_USUARIO,APELLIDOS,COD_POSTAL,CONTRASENYA,CORREO,DIRECCION,FECHA_NAC,NICK,NOMBRE,NUM_DIRECCION,PROVINCIA,USUARIO_ADMIN) VALUES (NEXTVAL('hibernate_sequence'), 'usuario', 1234, '$2a$10$ViuW2M5FN7PYOrtDZoz/H.GPTOR4uXXIf3KnWAan4K/uLnvOZZznu', 'usuario@usuario.com', 'usuario', TO_DATE('01/01/1999', 'DD/MM/YYYY'), 'usuario', 'usuario', 1, 'usuario', false); 

INSERT INTO USUARIO(ID_USUARIO,APELLIDOS,COD_POSTAL,CONTRASENYA,CORREO,DIRECCION,FECHA_NAC,NICK,NOMBRE,NUM_DIRECCION,PROVINCIA,USUARIO_ADMIN) VALUES (NEXTVAL('hibernate_sequence'), 'admin', 1234, '$2a$10$QH/Inj04qQY3/8UQxaw5F.7vZxTTKtZexzLgmSVgoPi.k8GezFIsi', 'admin@admin.com', 'admin', TO_DATE('01/01/1999', 'DD/MM/YYYY'), 'admin', 'admin', 1, 'usuario', true); 

 INSERT INTO CATEGORIA(ID_CATEGORIA,NOMBREC) VALUES (NEXTVAL('hibernate_sequence'), 'Discografía');

 INSERT INTO CATEGORIA(ID_CATEGORIA,NOMBREC) VALUES (NEXTVAL('hibernate_sequence'), 'Instrumentos');

 INSERT INTO CATEGORIA(ID_CATEGORIA,NOMBREC) VALUES (NEXTVAL('hibernate_sequence'), 'Otros');

INSERT INTO CONCIERTO(ID,DESCRIPCION,FECHA_PUBL,IMAGE,NOMBRE,PVP,STOCK,ARTISTA,FECHA_CONC,LUGAR_CONC,LINEA_PEDIDO_ID_LINEA_PEDIDO) VALUES (NEXTVAL('hibernate_sequence'), 'Concierto Wembley Queen', TO_DATE('27/05/2019', 'DD/MM/YYYY'), null, 'Concierto Wembley Queen', 50, true, 'Queen', TO_DATE('29/05/2019', 'DD/MM/YYYY'), 'Manchester', null);

INSERT INTO CONCIERTO(ID,DESCRIPCION,FECHA_PUBL,IMAGE,NOMBRE,PVP,STOCK,ARTISTA,FECHA_CONC,LUGAR_CONC,LINEA_PEDIDO_ID_LINEA_PEDIDO) VALUES (NEXTVAL('hibernate_sequence'), 'Concierto Imagine Dragons Barcelona', TO_DATE('27/05/2019', 'DD/MM/YYYY'), null, 'Concierto Imagine Dragons Barcelona', 70, true, 'Imagine Dragons', TO_DATE('29/06/2019', 'DD/MM/YYYY'), 'Barcelona', null);
